backend/screener_daily_USA/urls.py
from django.urls import path
from . import views

app_name = 'screener_daily_USA'

urlpatterns = [
    path('screener/', views.screener_html, name='screener'),
    path('stock_heatmap_SPX/', views.stock_heatmap_SPX_html, name='stock_heatmap_SPX'),
    path('stock_heatmap_NDX/', views.stock_heatmap_NDX_html, name='stock_heatmap_NDX'),
]

backend/screener_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('screener_USA/', include('screener_daily_USA.urls')),
    path('auth_telegram_bot/', include('auth_telegram_bot.urls')),
    path('', views.index_html, name='index'),
    path('contact_us', views.contact_us_html, name='contact_us'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

backend/screener_daily_USA/models.py
from django.db import models

class Stock_Merge_All_Tables(models.Model):
    symbol = models.CharField(max_length=255, primary_key=True)

    # Поля из Stock_Data_Overview
    name = models.CharField(max_length=255, null=True)
    exchange = models.CharField(max_length=255, null=True)
    description = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    typespecs = models.CharField(max_length=255, null=True)
    close = models.FloatField(null=True)
    currency = models.CharField(max_length=255, null=True)
    change = models.FloatField(null=True)
    volume = models.FloatField(null=True)
    relative_volume_10d_calc = models.FloatField(null=True)
    market_cap_basic = models.FloatField(null=True)
    fundamental_currency_code = models.CharField(max_length=255, null=True)
    price_earnings_ttm = models.FloatField(null=True)
    earnings_per_share_diluted_ttm = models.FloatField(null=True)
    earnings_per_share_diluted_yoy_growth_ttm = models.FloatField(null=True)
    dividends_yield_current = models.FloatField(null=True)
    sector_tr = models.CharField(max_length=255, null=True)
    market = models.CharField(max_length=255, null=True)
    sector = models.CharField(max_length=255, null=True)

    # Поля из Stock_Data_Performance
    perf_w = models.FloatField(null=True)
    perf_1m = models.FloatField(null=True)
    perf_3m = models.FloatField(null=True)
    perf_6m = models.FloatField(null=True)
    perf_ytd = models.FloatField(null=True)
    perf_y = models.FloatField(null=True)
    perf_5y = models.FloatField(null=True)
    perf_10y = models.FloatField(null=True)
    perf_all = models.FloatField(null=True)
    volatility_w = models.FloatField(null=True)
    volatility_m = models.FloatField(null=True)

    # Поля из Stock_Data_Valuation
    perf_1y_market_cap = models.FloatField(null=True)
    price_earnings_growth_ttm = models.FloatField(null=True)
    price_sales_current = models.FloatField(null=True)
    price_book_fq = models.FloatField(null=True)
    price_to_cash_f_operating_activities_ttm = models.FloatField(null=True)
    price_free_cash_flow_ttm = models.FloatField(null=True)
    price_to_cash_ratio = models.FloatField(null=True)
    enterprise_value_current = models.FloatField(null=True)
    enterprise_value_to_revenue_ttm = models.FloatField(null=True)
    enterprise_value_to_ebit_ttm = models.FloatField(null=True)
    enterprise_value_ebitda_ttm = models.FloatField(null=True)

    # Поля из Stock_Data_Dividends
    dps_common_stock_prim_issue_fy = models.FloatField(null=True)
    dps_common_stock_prim_issue_fq = models.FloatField(null=True)
    dividends_yield = models.FloatField(null=True)
    dividend_payout_ratio_ttm = models.FloatField(null=True)
    dps_common_stock_prim_issue_yoy_growth_fy = models.FloatField(null=True)
    continuous_dividend_payout = models.FloatField(null=True)
    continuous_dividend_growth = models.FloatField(null=True)

    # Поля из Stock_Data_Profitability
    gross_margin_ttm = models.FloatField(null=True)
    operating_margin_ttm = models.FloatField(null=True)
    pre_tax_margin_ttm = models.FloatField(null=True)
    net_margin_ttm = models.FloatField(null=True)
    free_cash_flow_margin_ttm = models.FloatField(null=True)
    return_on_assets_fq = models.FloatField(null=True)
    return_on_equity_fq = models.FloatField(null=True)
    return_on_invested_capital_fq = models.FloatField(null=True)
    research_and_dev_ratio_ttm = models.FloatField(null=True)
    sell_gen_admin_exp_other_ratio_ttm = models.FloatField(null=True)

    # Поля из Stock_Data_Income_Statement
    total_revenue_ttm = models.FloatField(null=True)
    total_revenue_yoy_growth_ttm = models.FloatField(null=True)
    gross_profit_ttm = models.FloatField(null=True)
    oper_income_ttm = models.FloatField(null=True)
    net_income_ttm = models.FloatField(null=True)
    ebitda_ttm = models.FloatField(null=True)

    # Поля из Stock_Data_Balance_Sheet
    total_assets_fq = models.FloatField(null=True)
    total_current_assets_fq = models.FloatField(null=True)
    cash_n_short_term_invest_fq = models.FloatField(null=True)
    total_liabilities_fq = models.FloatField(null=True)
    total_debt_fq = models.FloatField(null=True)
    net_debt_fq = models.FloatField(null=True)
    total_equity_fq = models.FloatField(null=True)
    current_ratio_fq = models.FloatField(null=True)
    quick_ratio_fq = models.FloatField(null=True)
    debt_to_equity_fq = models.FloatField(null=True)
    cash_n_short_term_invest_to_total_debt_fq = models.FloatField(null=True)

    # Поля из Stock_Data_Cash_Flow
    cash_f_operating_activities_ttm = models.FloatField(null=True)
    cash_f_investing_activities_ttm = models.FloatField(null=True)
    cash_f_financing_activities_ttm = models.FloatField(null=True)
    free_cash_flow_ttm = models.FloatField(null=True)
    capital_expenditures_ttm = models.FloatField(null=True)

    # Поля из SPX_Components и NDX_Components
    spx_components = models.CharField(max_length=255, null=True)
    ndx_components = models.CharField(max_length=255, null=True)

    # Поля из Stock_Data_Indicators
    ADR_percent = models.FloatField(null=True)
    SMA_10 = models.FloatField(null=True)
    SMA_20 = models.FloatField(null=True)
    SMA_50 = models.FloatField(null=True)
    SMA_100 = models.FloatField(null=True)
    SMA_150 = models.FloatField(null=True)
    SMA_200 = models.FloatField(null=True)
    high_10 = models.FloatField(null=True)
    high_20 = models.FloatField(null=True)
    high_50 = models.FloatField(null=True)
    high_100 = models.FloatField(null=True)
    high_150 = models.FloatField(null=True)
    high_200 = models.FloatField(null=True)
    high_1y = models.FloatField(null=True)
    low_10 = models.FloatField(null=True)
    low_20 = models.FloatField(null=True)
    low_50 = models.FloatField(null=True)
    low_100 = models.FloatField(null=True)
    low_150 = models.FloatField(null=True)
    low_200 = models.FloatField(null=True)
    low_1y = models.FloatField(null=True)
    quick_filter_1=models.FloatField(null=True)
    quick_filter_2=models.FloatField(null=True)
    quick_filter_3=models.FloatField(null=True)
    quick_filter_4=models.FloatField(null=True)
    quick_filter_5=models.FloatField(null=True)
    quick_filter_6=models.FloatField(null=True)

    class Meta:
        app_label = 'screener_daily_USA'
        db_table = 'stock_merge_all_tables_USA'


class Stock_Data_Indicators(models.Model):
    symbol = models.CharField(max_length=255, primary_key=True)
    ADR_percent = models.FloatField(null=True)
    SMA_10 = models.FloatField(null=True)
    SMA_20 = models.FloatField(null=True)
    SMA_50 = models.FloatField(null=True)
    SMA_100 = models.FloatField(null=True)
    SMA_150 = models.FloatField(null=True)
    SMA_200 = models.FloatField(null=True) 
    high_10 = models.FloatField(null=True)
    high_20 = models.FloatField(null=True)
    high_50 = models.FloatField(null=True)
    high_100 = models.FloatField(null=True)
    high_150 = models.FloatField(null=True)
    high_200 = models.FloatField(null=True)
    high_1y = models.FloatField(null=True)
    low_10 = models.FloatField(null=True)
    low_20 = models.FloatField(null=True)
    low_50 = models.FloatField(null=True)
    low_100 = models.FloatField(null=True)
    low_150 = models.FloatField(null=True)
    low_200 = models.FloatField(null=True)
    low_1y = models.FloatField(null=True)
    quick_filter_1=models.FloatField(null=True)
    quick_filter_2=models.FloatField(null=True)
    quick_filter_3=models.FloatField(null=True)
    quick_filter_4=models.FloatField(null=True)
    quick_filter_5=models.FloatField(null=True)
    quick_filter_6=models.FloatField(null=True)

    class Meta:
        app_label = 'screener_daily_USA'
        db_table = 'stock_data_indicators_USA'


class Stock_Data_Balance_Sheet(models.Model):
    symbol = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255, null=True)  
    exchange = models.CharField(max_length=255, null=True)  
    description = models.CharField(max_length=255, null=True)  
    logoid = models.CharField(max_length=255, null=True)  
    update_mode = models.CharField(max_length=255, null=True)  
    type = models.CharField(max_length=50, null=True)  
    typespecs = models.CharField(max_length=255, null=True)  
    total_assets_fq = models.FloatField(null=True)
    fundamental_currency_code = models.CharField(max_length=255, null=True)
    total_current_assets_fq = models.FloatField(null=True)
    cash_n_short_term_invest_fq = models.FloatField(null=True)
    total_liabilities_fq = models.FloatField(null=True)
    total_debt_fq = models.FloatField(null=True)
    net_debt_fq = models.FloatField(null=True)
    total_equity_fq = models.FloatField(null=True)
    current_ratio_fq = models.FloatField(null=True)
    quick_ratio_fq = models.FloatField(null=True)
    debt_to_equity_fq = models.FloatField(null=True)
    cash_n_short_term_invest_to_total_debt_fq = models.FloatField(null=True)

    class Meta:
        app_label = 'screener_daily_USA'  
        db_table = 'stock_data_balance_sheet_USA'  

class Stock_Data_Cash_Flow(models.Model):
    symbol = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255, null=True)
    exchange = models.CharField(max_length=255, null=True)
    description = models.CharField(max_length=255, null=True)
    logoid = models.CharField(max_length=255, null=True)
    update_mode = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=50, null=True)
    typespecs = models.CharField(max_length=255, null=True)
    cash_f_operating_activities_ttm = models.FloatField(null=True)
    fundamental_currency_code = models.CharField(max_length=255, null=True)
    cash_f_investing_activities_ttm = models.FloatField(null=True)
    cash_f_financing_activities_ttm = models.FloatField(null=True)

backend/screener_daily_USA/views.py
from auth_telegram_bot.utils import ip_access_required
from django.shortcuts import render
from .models import Stock_Merge_All_Tables
import json

@ip_access_required
def screener_html(request):
    stock_data = Stock_Merge_All_Tables.objects.all().values()
    data = list(stock_data) 
    return render(request, 'screener.html', {'data': json.dumps(data)}) 

@ip_access_required
def stock_heatmap_SPX_html(request):
    return render(request, 'stock_heatmap_SPX.html')

@ip_access_required
def stock_heatmap_NDX_html(request):
    return render(request, 'stock_heatmap_NDX.html')

backend/screener_daily_USA/templates/stock_heatmap_NDX.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Stock Heatmap - Nasdaq 100 Index</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href={% static 'pages/css/styles.css' %} rel="stylesheet" />
        <link rel="icon" type="image/x-icon" href={% static 'pages/assets/img/favicon.png' %} />
        <script data-search-pseudo-elements defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js" crossorigin="anonymous"></script>
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript" >
            (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
            m[i].l=1*new Date();
            for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
            k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
        
            ym(99197622, "init", {
                clickmap:true,
                trackLinks:true,
                accurateTrackBounce:true
            });
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/99197622" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->        
    </head>
    <body class="nav-fixed">
        <nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" id="sidenavAccordion">
            <!-- Sidenav Toggle Button-->
            <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle"><i data-feather="menu"></i></button>
            <!-- Navbar Brand-->
            <a class="navbar-brand pe-3 ps-4 ps-lg-2" href="{% url 'index' %}">Stock Screener Pro</a>
            <!-- Navbar Search Input-->
            <form class="form-inline me-auto d-none d-lg-block me-3">
                <div class="input-group input-group-joined input-group-solid">
                    <input class="form-control pe-0" type="search" placeholder="Search" aria-label="Search" />
                    <div class="input-group-text"><i data-feather="search"></i></div>
                </div>
            </form>
            <!-- Navbar Items-->
            <ul class="navbar-nav align-items-center ms-auto">
                <!-- Notifications Dropdown-->
                <li class="nav-item dropdown no-caret d-none d-sm-block me-3 dropdown-notifications">
                    <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownAlerts" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="bell"></i></a>
                    <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownAlerts">
                        <h6 class="dropdown-header dropdown-notifications-header">
                            <i class="me-2" data-feather="bell"></i>
                            Notifications
                        </h6>
                        <div class="dropdown-notifications-footer text-center">No notifications</div>
                    </div>
                </li>
                <!-- Messages Dropdown-->
                <li class="nav-item dropdown no-caret d-none d-sm-block me-3 dropdown-notifications">
                    <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownMessages" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="mail"></i></a>
                    <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownMessages">
                        <h6 class="dropdown-header dropdown-notifications-header">
                            <i class="me-2" data-feather="mail"></i>
                            Message Center
                        </h6>
                        <div class="dropdown-notifications-footer text-center">No messages</div>
                    </div>
                </li>
                <!-- Contact us Dropdown-->
                <li class="nav-item dropdown no-caret d-none d-md-block me-3">
                    <a class="nav-link dropdown-toggle" href="{% url 'contact_us' %}">
                        <div class="fw-500">Contact us</div>
                    <i class="fas fa-chevron-right dropdown-arrow"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sidenav shadow-right sidenav-light">
                    <div class="sidenav-menu">
                        <div class="nav accordion" id="accordionSidenav">
                            <!-- Sidenav Menu Heading (U.S. Stock Market)-->
                            <div class="sidenav-menu-heading">U.S. Stock Market</div>
                            <!-- Sidenav Accordion -->
                            <a class="nav-link collapsed" href="{% url 'screener_daily_USA:screener' %}">
                                <div class="nav-link-icon"><i data-feather="globe"></i></div>
                                U.S. Stock Screener
                                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="sidenav-menu-heading">Stock Heatmap</div>
                            <a class="nav-link collapsed" href="{% url 'screener_daily_USA:stock_heatmap_SPX' %}">
                                <div class="nav-link-icon"><i data-feather="bar-chart"></i></div>
                                S&P 500 Index
                                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <a class="nav-link collapsed" href="{% url 'screener_daily_USA:stock_heatmap_NDX' %}">
                                <div class="nav-link-icon"><i data-feather="layout"></i></div>
                                Nasdaq 100 Index
                                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
                        <div class="container-xl px-4">
                            <div class="page-header-content pt-4">
                                <div class="row align-items-center justify-content-between">
                                    <div class="col-auto mt-4">
                                        <h1 class="page-header-title">
                                            <div class="page-header-icon"><i data-feather="layout"></i></div>
                                            Stock Heatmap - Nasdaq 100 Index
                                        </h1>
                                        <div class="page-header-subtitle">Get a macro-level view of stocks, ideal for analyzing by sector or market cap.</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </header>
                    <!-- Main page content-->
                    <div class="container-fluid px-4 mt-n10">
                        <div class="row">
                            <div class="card mb-4" style="height: 950px; width: 100%;">
                                <div class="card-header">Nasdaq 100 Index</div>
                                <div class="card-body">
                                    <div class="tradingview-widget-container">
                                        <div class="tradingview-widget-container__widget"></div>
                                        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-stock-heatmap.js" async>
                                        {
                                        "exchanges": [],
                                        "dataSource": "NASDAQ100",
                                        "grouping": "sector",
                                        "blockSize": "market_cap_basic",
                                        "blockColor": "change",
                                        "locale": "en",
                                        "symbolUrl": "",
                                        "colorTheme": "light",
                                        "hasTopBar": false,
                                        "isDataSetEnabled": false,
                                        "isZoomEnabled": true,
                                        "hasSymbolTooltip": true,
                                        "isMonoSize": false,
                                        "width": "100%",
                                        "height": "100%"
                                        }
                                        </script>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="footer-admin mt-auto footer-light">
                    <div class="container px-5">
                        <div class="row gx-5 align-items-center justify-content-center">
                            <div class="mb-2 text-center">created by lazycat7777</div>
                            <div class="icon-list-social mb-0 justify-content-center">
                                <a class="icon-list-social-link" href="https://t.me/lazycat7777"><i class="fab fa-telegram"></i></a>
                                <a class="icon-list-social-link" href="https://www.reddit.com/user/lazycat7777/"><i class="fab fa-reddit"></i></a>
                                <a class="icon-list-social-link" href="https://github.com/lazycat7777"><i class="fab fa-github"></i></a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src={% static 'pages/js/scripts.js' %}></script>
    </body>
</html>